# Generated by Django 3.1.3 on 2020-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Word', max_length=255)),
                ('description', models.TextField(help_text='Description')),
                ('video_id', models.CharField(blank=True, help_text='Video ID', max_length=255)),
            ],
        ),
    ]
