# Generated by Django 3.1.3 on 2020-11-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='video',
            field=models.FileField(default='default.mp4', upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='word',
            name='video_id',
            field=models.CharField(help_text='Youtube video ID', max_length=255, null=True),
        ),
    ]
