# Generated by Django 3.1.3 on 2020-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20201113_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(default='videos/default.mp4', upload_to='videos'),
        ),
    ]
