# Generated by Django 3.1.3 on 2020-11-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20201113_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='video_id',
        ),
    ]
