# Generated by Django 3.1.3 on 2020-11-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_remove_word_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
