# Generated by Django 3.1.3 on 2020-11-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20201113_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('word',)},
        ),
    ]
