# Generated by Django 3.1.3 on 2020-11-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20201113_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
